'use strict';

/**
 * src/audit.js
 *
 * AI-driven (but deterministically generated) security and scope-violation 
 * auditing for team PRs. Generates a structured Markdown report.
 */

const { getViolations } = require('./git');

/**
 * Run an audit against a base branch and output a Markdown report.
 * @param {string} baseBranch 
 */
function runAudit(baseBranch = 'origin/main') {
  console.log(`Running audit against base branch: ${baseBranch}...`);
  
  // We don't enforce test coverage gate strictly for the audit report by default,
  // but we could if we passed `true` here. We'll pass `true` to show all possible violations.
  const result = getViolations(baseBranch, true);

  if (result.error) {
    console.error(`\n❌ Audit failed: ${result.error}`);
    process.exit(1);
  }

  const { violations } = result;

  console.log('\n' + '='.repeat(60));
  console.log('📝 DRIFTLOCK AUDIT REPORT');
  console.log('='.repeat(60) + '\n');

  if (violations.length === 0) {
    console.log('## ✅ Scope Audit: PASSED\n');
    console.log('No scope violations, secret leaks, or test coverage gaps detected in this PR.');
    return;
  }

  console.log(`## ❌ Scope Audit: FAILED (${violations.length} violations)\n`);

  const secrets = violations.filter(v => v.type === 'secret');
  const files = violations.filter(v => v.type === 'file');
  const functions = violations.filter(v => v.type === 'function' || v.type === 'function-missing');
  const testGate = violations.filter(v => v.type === 'test-gate');

  if (secrets.length > 0) {
    console.log('### 🚨 Critical Security Leaks');
    for (const v of secrets) {
      console.log(`- **${v.file}**: ${v.message}`);
    }
    console.log('');
  }

  if (files.length > 0) {
    console.log('### 🔒 Locked File Violations');
    for (const v of files) {
      console.log(`- **${v.file}**: ${v.message}`);
    }
    console.log('');
  }

  if (functions.length > 0) {
    console.log('### 🎯 Locked Function Violations');
    for (const v of functions) {
      console.log(`- **${v.file}** (\`${v.fn}\`): ${v.message}`);
    }
    console.log('');
  }

  if (testGate.length > 0) {
    console.log('### 🧪 Test Coverage Gate');
    for (const v of testGate) {
      console.log(`- ${v.message}`);
    }
    console.log('');
  }

  console.log('---\n*Report generated by driftlock audit*');
  
  // Exit non-zero so CI pipelines fail.
  process.exit(1);
}

module.exports = { runAudit };
